//! Integration test for the `#[smsg("descriptors.pb")]` macro: it must generate
//! `EnvelopeMeta` impls that match the runtime `Schema`, and the typed envelope
//! API must work without any runtime schema object.

use smsg_macro::smsg;
use soul_msg::{Envelope, EnvelopeError, EnvelopeMeta, Schema};

// `chat.rs` is generated by prost-build in `smsg_macro/build.rs` from the same
// `.proto` files that produced `tests/fixtures/descriptors.pb`.
#[smsg("tests/fixtures/descriptors.pb")]
pub mod chat {
    include!(concat!(env!("OUT_DIR"), "/chat.rs"));
}

fn fresh_schema() -> Schema {
    // Use the freshly generated descriptor set so a stale fixture fails the test.
    let bytes = include_bytes!(concat!(env!("OUT_DIR"), "/descriptors.pb"));
    Schema::from_descriptor_set(bytes).unwrap()
}

#[test]
fn typed_meta_matches_runtime_schema() {
    let schema = fresh_schema();
    let meta = schema.by_name("chat.ChatMessage").unwrap();
    assert_eq!(chat::ChatMessage::NAME_HASH, meta.name_hash);
    assert_eq!(chat::ChatMessage::VERSION_HASH, meta.version_hash);
    assert_eq!(chat::ChatMessage::FULL_NAME, meta.full_name);

    let pos = schema.by_name("chat.Position").unwrap();
    assert_eq!(chat::Position::NAME_HASH, pos.name_hash);
    assert_eq!(chat::Position::VERSION_HASH, pos.version_hash);
    assert_eq!(chat::Position::FULL_NAME, pos.full_name);
}

#[test]
fn typed_roundtrip_without_schema() {
    let msg = chat::ChatMessage {
        sender: "Alice".to_string(),
        content: "Hello, World!".to_string(),
        timestamp: 1_699_999_999,
    };
    let bytes = Envelope::new_typed(&msg).to_bytes();
    let decoded: chat::ChatMessage = Envelope::try_deserialize_typed(&bytes).unwrap();
    assert_eq!(decoded, msg);
}

#[test]
fn typed_strict_rejects_type_mismatch() {
    let pos = chat::Position {
        x: 1.0,
        y: 2.0,
        z: 3.0,
    };
    let bytes = Envelope::new_typed(&pos).to_bytes();
    let result: Result<chat::ChatMessage, EnvelopeError> = Envelope::try_deserialize_typed(&bytes);
    assert!(matches!(result, Err(EnvelopeError::TypeMismatch { .. })));
}

#[test]
fn typed_nested_roundtrip() {
    let msg = chat::RobotState {
        name: "R2-D2".to_string(),
        position: Some(chat::Position {
            x: 100.5,
            y: 200.5,
            z: 300.5,
        }),
        status: 42,
    };
    let bytes = Envelope::new_typed(&msg).to_bytes();
    let decoded: chat::RobotState = Envelope::try_deserialize_typed(&bytes).unwrap();
    assert_eq!(decoded, msg);
}
