#!/usr/bin/env python3
"""Verify byte-for-byte consistency of the smsg envelope between Python and Rust,
using the `soulmsg` Python binding.

Reads the shared descriptors.pb (generated by protoc) and golden.json (dumped by the
Rust `dump_golden` example), rebuilds the same messages with Python protobuf, and
asserts payload/hash/envelope bytes match the Rust output exactly.
"""
import json
import os
import sys

from google.protobuf import descriptor_pb2, descriptor_pool, message_factory

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "..", "bindings", "python"))
from soulmsg import Envelope, Schema  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
VERIF_DIR = os.path.dirname(HERE)
DESCRIPTORS = os.path.join(VERIF_DIR, "descriptors.pb")
GOLDEN = os.path.join(VERIF_DIR, "golden.json")


def main() -> int:
    with open(DESCRIPTORS, "rb") as fh:
        fds = descriptor_pb2.FileDescriptorSet.FromString(fh.read())
    pool = descriptor_pool.DescriptorPool()
    for f in fds.file:
        pool.Add(f)

    schema = Schema.from_descriptor_bytes(open(DESCRIPTORS, "rb").read())
    golden = json.load(open(GOLDEN, encoding="utf-8"))["messages"]
    failures = []

    for full_name, expected in golden.items():
        meta = schema.by_name(full_name)
        assert meta is not None, f"message not found: {full_name}"

        cls = message_factory.GetMessageClass(pool.FindMessageTypeByName(full_name))
        msg = cls()
        if full_name == "chat.ChatMessage":
            msg.sender = "Alice"
            msg.content = "Hello, World!"
            msg.timestamp = 1_699_999_999
        elif full_name == "chat.RobotState":
            msg.name = "R2-D2"
            msg.position.x = 100.5
            msg.position.y = 200.5
            msg.position.z = 300.5
            msg.status = 42
        else:
            raise AssertionError(f"unknown fixture message: {full_name}")

        wire = Envelope.new(msg, meta)
        decoded = Envelope.try_deserialize(wire, meta, cls)
        assert decoded == msg

        checks = {
            "name_hash": meta.name_hash.hex(),
            "version_hash": meta.version_hash.hex(),
            "payload": msg.SerializeToString().hex(),
            "envelope": wire.hex(),
        }
        for key, actual in checks.items():
            if actual != expected[key]:
                failures.append(f"{full_name}.{key}:\n  rust = {expected[key]}\n  python = {actual}")

        ok = all(checks[k] == expected[k] for k in checks)
        print(f"[python] {full_name}: match" if ok else f"[python] {full_name}: MISMATCH")

    if failures:
        print("\n".join(failures))
        return 1
    print("\n[python] PASS: byte-for-byte identical to Rust (via soulmsg binding)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
