#!/usr/bin/env python3
"""Verify byte-for-byte consistency of the smsg_proto envelope between Python and Rust.

Reads the shared descriptors.pb (generated by protoc) and golden.json (dumped by the
Rust `dump_golden` example), rebuilds the same messages with Python protobuf, and
asserts payload/hash/envelope bytes match the Rust output exactly.
"""
import json
import os
import struct
import sys

import blake3
from google.protobuf import descriptor_pb2, descriptor_pool, message_factory

HERE = os.path.dirname(os.path.abspath(__file__))
VERIF_DIR = os.path.dirname(HERE)
DESCRIPTORS = os.path.join(VERIF_DIR, "descriptors.pb")
GOLDEN = os.path.join(VERIF_DIR, "golden.json")

NAME_DOMAIN = b"smsg_proto:name:v1\0"
VERSION_DOMAIN = b"smsg_proto:version:v1\0"


def seg(b: bytes) -> bytes:
    return struct.pack("<I", len(b)) + b


def name_hash(short_name: str) -> str:
    h = blake3.blake3()
    h.update(NAME_DOMAIN)
    h.update(seg(short_name.encode()))
    return h.hexdigest()


def version_hash(full_name: str, msg_desc) -> str:
    h = blake3.blake3()
    h.update(VERSION_DOMAIN)
    h.update(seg(full_name.encode()))
    h.update(struct.pack("<I", len(msg_desc.field)))
    for f in msg_desc.field:
        h.update(seg(f.name.encode()))
        h.update(struct.pack("<I", f.number))
        h.update(struct.pack("<I", f.type))
        if f.type_name:
            h.update(seg(f.type_name.encode()))
    return h.hexdigest()


def envelope_bytes(name_h: bytes, version_h: bytes, payload: bytes) -> bytes:
    return name_h + version_h + struct.pack("<I", len(payload)) + payload


def main() -> int:
    with open(DESCRIPTORS, "rb") as fh:
        fds = descriptor_pb2.FileDescriptorSet.FromString(fh.read())

    pool = descriptor_pool.DescriptorPool()
    for f in fds.file:
        pool.Add(f)

    golden = json.load(open(GOLDEN, encoding="utf-8"))["messages"]
    failures = []

    for full_name, expected in golden.items():
        short = full_name.split(".")[-1]
        # Find the DescriptorProto for this message.
        msg_desc = None
        for f in fds.file:
            for m in f.message_type:
                cand = f"{f.package}.{m.name}"
                if cand == full_name or (cand.endswith(full_name)):
                    msg_desc = m
                    break
            if msg_desc is not None:
                break
        assert msg_desc is not None, f"message not found: {full_name}"

        nh = bytes.fromhex(name_hash(short))
        vh = bytes.fromhex(version_hash(full_name, msg_desc))

        # Build and encode the same logical message as the Rust example.
        cls = message_factory.GetMessageClass(pool.FindMessageTypeByName(full_name))
        msg = cls()
        if full_name == "chat.ChatMessage":
            msg.sender = "Alice"
            msg.content = "Hello, World!"
            msg.timestamp = 1_699_999_999
        elif full_name == "chat.RobotState":
            msg.name = "R2-D2"
            msg.position.x = 100.5
            msg.position.y = 200.5
            msg.position.z = 300.5
            msg.status = 42
        else:
            raise AssertionError(f"unknown fixture message: {full_name}")

        payload = msg.SerializeToString()
        envelope = envelope_bytes(nh, vh, payload)

        checks = {
            "name_hash": nh.hex(),
            "version_hash": vh.hex(),
            "payload": payload.hex(),
            "envelope": envelope.hex(),
        }
        for key, actual in checks.items():
            if actual != expected[key]:
                failures.append(f"{full_name}.{key}:\n  rust   = {expected[key]}\n  python = {actual}")

        print(f"[python] {full_name}: name/version/payload/envelope all match rust" if not any(
            checks[k] != expected[k] for k in checks
        ) else f"[python] {full_name}: MISMATCH")

    if failures:
        print("\n".join(failures))
        return 1
    print("\n[python] PASS: byte-for-byte identical to Rust for all messages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
