[package]
name = "soul_msg-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
soul_msg = { path = ".." }
prost = "0.14"
prost-types = "0.14"

[[bin]]
name = "fuzz_envelope"
path = "fuzz_targets/fuzz_envelope.rs"
test = false
doc = false
