[package]
name = "smsg_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
smsg_core = { path = "../smsg_core" }
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
miette = { version = "7", features = ["fancy"] }
thiserror = "2.0"
toml = "0.8"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"

[dev-dependencies]
zenoh-ext = "1.7"
toml = "0.8"
tempfile = "3"
soul_msg = { path = ".." }
